kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

mc_version=1.21.1
neoforge_version=21.1.248
parchment_mappings_version=2024.11.17

mod_id=dye_the_world
mod_version=0.0.0-dev
release_type=release
mod_name=Dye The World!
mod_author=possible_triangle
maven_group=com.possible-triangle
mod_description=Compatibility for the Dye Depot mod

kotlin_forge_version=5.8.0

repository=pssbletrngle/dyetheworld
modrinth_project_id=naUMeOvG
curseforge_project_id=1135725
