kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

mc_version=1.20.1
forge_version=47.4.20
parchment_mappings_version=2023.09.03
java_version=17

mod_id=dye_the_world
mod_version=0.0.0-dev
release_type=release
mod_name=Dye The World!
mod_author=possible_triangle
maven_group=com.possible-triangle
mod_description=Compatibility for the Dye Depot mod

kotlin_forge_version=4.3.0
mixin_extras_version=0.4.1

repository=pssbletrngle/dyetheworld
modrinth_project_id=naUMeOvG
curseforge_project_id=1135725
