modLoader = "kotlinforforge"
loaderVersion = "[5.8.0,)"
license = "https://github.com/${repository}/blob/1.21.x/LICENSE.txt"
issueTrackerURL = "https://github.com/${repository}/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''Compatiblity for the Dye Depot mod'''
updateJSONURL = "https://api.modrinth.com/updates/dye-the-world/forge_updates.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
versionRange = "[1.21,1.21.1)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="kotlinforforge"
versionRange="[5.8.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="dye_depot"
versionRange="[2.0.0-neoforge,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "create"
type = "optional"
versionRange = "[6.0.0,6.1.0)"
ordering="AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "another_furniture"
type = "optional"
versionRange = "*"
ordering="AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "supplementaries"
type = "optional"
versionRange = "*"
ordering="AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "chalk"
type = "optional"
versionRange = "*"
ordering="AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "upgrade_aquatic"
type = "optional"
versionRange = "*"
ordering="AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "farmersdelight"
type = "optional"
versionRange = "*"
ordering="AFTER"
side = "BOTH"

[[mixins]]
config="${mod_id}.mixins.json"