[versions]
multikulti = "1.21.1-2.0.3"
flywheel = "1.0.6"
create-simulated = "1.3.1"

[libraries]
registrate = { group = "com.tterrag.registrate", name = "Registrate", version = "MC1.21-1.3.0+67" }
multikulti-core = { group = "com.possible-triangle", name = "multikulti-core-neoforge", version.ref = "multikulti" }
multikulti-datagen = { group = "com.possible-triangle", name = "multikulti-datagen-neoforge", version.ref = "multikulti" }

create = { group = "com.simibubi.create", name = "create-1.21.1", version = "6.0.10-281" }
ponder = { group = "net.createmod.ponder", name = "ponder-neoforge", version = "1.0.85+mc1.21.1" }
flywheel = { group = "dev.engine-room.flywheel", name = "flywheel-neoforge-1.21.1", version.ref = "flywheel" }
flywheel-api = { group = "dev.engine-room.flywheel", name = "flywheel-neoforge-api-1.21.1", version.ref = "flywheel" }

sable = { group = "dev.ryanhcode.sable", name = "sable-neoforge-1.21.1", version = "2.0.4" }
create-simulated = { group = "dev.simulated_team.simulated", name = "simulated-neoforge-1.21.1", version.ref = "create-simulated" }
create-aeronautics = { group = "dev.eriksonn.aeronautics", name = "aeronautics-neoforge-1.21.1", version.ref = "create-simulated" }

jei = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version = "19.21.0.247" }

dye-depot = { group = "com.ninni.dye_depot", name = "dye_depot-neoforge", version = "1.21.1-2.1.1" }

windswept = { group = "com.rosemods", name = "windswept-1.21.1", version = "4.0.0-SNAPSHOT" }
