name = "Arva"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "121f13098344b650ac2f604443e36d7d6ae7dbfcbbc32e01af4bd799998ddcbc"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
