name = "Arva"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f49e90c6bc71ef83a47cc89f7aa3378d38a2f5433e77d6173660ab0da9e6b214"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
