name: Release Polytone
on:
  workflow_dispatch:
    inputs:
      skip-cache:
        description: 'force upload even without changes?'
        type: boolean
        required: false
        default: false
  push:
    branches: [ "[0-9]+.[0-9]+.x" ]
    paths:
      - polytone/*.zip

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: 'gradle.properties'
          properties: 'mc_version'

      - id: cache
        uses: actions/cache@v4
        with:
          key: polytone-${{ steps.read_property.outputs.mc_version }}-${{ hashFiles('polytone/*.zip') }}
          path: modrinth-link.txt

      - uses: Kir-Antipov/mc-publish@v3.3
        id: publish
        if: steps.cache.outputs.cache-hit != 'true' || inputs.skip-cache
        with:
          modrinth-id: 2j2IcOdG
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            polytone/*.zip
          version: 1.0.${{ github.run_number }}
          game-versions: |
            ${{ steps.read_property.outputs.mc_version }}
          loaders: |
            minecraft
          dependencies: |
            polytone

      - run: echo ${{ steps.publish.outputs.modrinth-url }} > modrinth-link.txt
        if: steps.cache.outputs.cache-hit != 'true' || inputs.skip-cache